#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run eslint . --ext .js

echo "===\n>> Pre-push Hook: Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|staging|develop)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR."
fi

echo ">> Finish checking branch name.\n==="